#!/usr/bin/env bash
# DO NOT EDIT THIS FILE

wordArray=(
'gut' 
'mann' 
'tausend dank' 
'guten tag'
)
meaningArray=(
'good / fine' 
'man' 
'a thousand thanks' 
'good day'
)
pronunciationArray=(
'goo-t' 
'mah-n' 
't-ow-zend dahnk' 
'gu-ten tag'
)
export wordArray
export meaningArray
export pronunciationArray
# chmod +x ~/.vocab-script
. ~/.vocab-script-de
exit 0