
#!/usr/bin/env bash
# DO NOT EDIT THIS FILE

wordArray=(
'gut' 

)
meaningArray=(
'good / fine' 

)
pronunciationArray=(
'goo-t' 

)
export wordArray
export meaningArray
export pronunciationArray
# chmod +x ~/.vocab-script
. ~/.vocab-script-de
exit 0
        